import React, { useEffect, useState } from "react";
import Head from "next/head";
import Link from "next/link";
import * as fs from "fs";
import InfiniteScroll from "react-infinite-scroll-component";

// import Image from "next/image";
import styles from "../styles/Home.module.css";

function Home(props) {
  const [blogs, setBlogs] = useState(props.allBlogs);

  const fetchData = async () => {
    let d = await fetch(
      `http://localhost:3000/api/blogs/?count=${blogs.length + 2}`
    );
    let data = await d.json();
    setBlogs(data);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script> */}

      <main className={styles.main}>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="/home-img.jpg"
            width={157}
            height={158}
            alt="Hunting Coder"
          />
        </div>
        <h1 className={styles.title}>
          <span className="mySpan">&lt;HuntingCoder/&gt;</span>
        </h1>

        <div>
          <h2 className={styles.h2}>Latest Blogs</h2>

          <InfiniteScroll
            dataLength={blogs.length} //This is important field to render the next data
            next={fetchData}
            hasMore={props.allCount > blogs.length}
            loader={<h4>Loading...</h4>}
            endMessage={
              <p style={{ textAlign: "center" }}>
                <b>Yay! You have seen it all</b>
              </p>
            }
            // below props only if you need pull down functionality
          >
            {blogs.map((blogItem) => (
              <div key={Math.random()} className={styles.blogItem}>
                <Link href={`/blogpost/${blogItem.slug}`}>
                  <h2>{blogItem.title}</h2>
                </Link>
                <p className={styles.blogItemp}>{blogItem.metadesc}...</p>
                <Link href={`/blogpost/${blogItem.slug}`}>
                  <button className={styles.btn}>Read More..</button>
                </Link>
              </div>
            ))}
          </InfiniteScroll>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps(context) {
  // Fetch data from external API
  let data = await fs.promises.readdir("blogdata");
  let allCount = data.length;
  let myfile;
  let allBlogs = [];

  for (let index = 0; index < 3; index++) {
    const item = data[index];
    // console.log(item);
    myfile = await fs.promises.readFile(`blogdata/${item}`, "utf-8");
    allBlogs.push(JSON.parse(myfile));
  }

  // Pass data to the page via props
  return { props: { allBlogs, allCount } };
}

export default Home;
